// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tebccrvgokmkclnjufxr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRlYmNjcnZnb2tta2Nsbmp1ZnhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQyMTY0MzEsImV4cCI6MjA5OTc5MjQzMX0.11AbVFL23zVrFMKtGEcLmyYBpmVJDQmeF5YqLHRqePY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});